/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Author } from './author';

export interface Book { 
    bookId?: number;
    title?: string;
    isStocked?: boolean;
    authorFk?: Author;
}