/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Author } from './author';


export interface Book { 
    bookId?: number;
    title?: string;
    isStocked?: boolean;
    authorFk?: Author;
}

